[libraries]
# Production
sparkJava = "com.sparkjava:spark-core:2.9.4"
logback = "ch.qos.logback:logback-classic:1.5.30"
hikari = "com.zaxxer:HikariCP:7.0.2"
flyway = "org.flywaydb:flyway-database-postgresql:12.0.1"
postgres = "org.postgresql:postgresql:42.7.10"

# Test
assertj = "org.assertj:assertj-core:3.27.7"
restAssured = "io.rest-assured:rest-assured:6.0.0"
testcontainers = "org.testcontainers:testcontainers:2.0.3"
wiremock = "com.github.tomakehurst:wiremock-jre8:3.0.1"

[plugins]
javaService = { id = "io.github.rieske.java-service", version = "1.0.2" }